name: just_CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main


env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: get the code
      uses: actions/checkout@v5.0.0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.4.2
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
      
    - name: getting the dependencies
      run: dotnet restore

    - name: Compile
      run: dotnet build --no-restore

    - name: Run tsts
      run: dotnet test --no-build
